### ISSUE TITLE
fastmul 实现复杂度错误

### ISSUE THREAD

**Issue by alphagocc** [VincentWei/PLZS#1]
https://github.com/VincentWei/PLZS/blob/a88e0f8a2c3f0689bdd0755a558bc0c00fcac583/source/classic-problems/high-precision-arithmetic/bigint.cpp#L375

经过分析容易知道该乘法复杂度为 $\mathcal{O}(n^2)$ 和朴素实现没有任何差距，甚至比朴素实现慢。

**Comment by alphagocc** [comment]
一般来说 fastmul 会期待一个 $\mathcal{O} (n log n)$ 的实现或至少 $\mathcal O (n^{1.5})$ 的实现

**Comment by VincentWei** [comment]
多谢！目前这个实现是初步的，并未用于 * 和 *= 运算符的实现。欢迎提交优化版本。

另外，代码需要优化和代码有错误是两码事。用词要准确，一如分析时间复杂度要严谨一般。

**Comment by VincentWei** [comment]
新增 `nttmul()` 实现，并使用 `nttmul()` 实现 * 和 *= 运算符的重载（仅在两个乘数的切片长度之和大于 8 时）。

原 `fastmul()` 调整为 `binmul()`，本质上使用的是 binary-lifting 算法，可作为参考实现。该算法的时间复杂度有待进一步分析，并通过计算 CPU 指令周期来进一步验证。

PS，<https://oi-wiki.org/math/poly/ntt/> 中给出的 NTT 参考实现存在问题：当有切片中存在大于 31595 的数（也就是多项式系数大于 31595）时不能正常工作。或者说，那段代码只能用于万进制以下的压位高精度实现。
